### ISSUE TITLE
Are you planning to provide a C++ version of the USB framework?

### ISSUE THREAD

**Issue by NicolasGoeddel** [nonolith/USB-XMEGA#3]
Hi,

I tested your usb-xmega stream example successfully with an ATXMega192A3U, so I decided to add more stuff to the AVR code and also to change the python code. So I added a new C++ class AD7606 (for an D/A converter), included the AD7606.h in the main file and added AD7606.cpp to the line saying "CPPSRC =" in the Makefile.

But to use the class in the main file I had to convert the main file and all its includes to C++ too. But before I go to work... Are you planning to provide a C++ version of the USB framework?

**Comment by kevinmehall** [comment]
I have no plans to make the library use C++, but you can certainly use it from C++ without converting any of the library files.

I would accept a pull request to wrap the header files in

```
#ifdef __cplusplus 
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
```
